spring:
  application:
    name: minecraft
server:
  port: 8081
security:
  hmac-secret: ${HMAC_SECRET}
  max-skew-seconds: 60
  header-ts: X-TS
  header-nonce: X-NONCE
  header-sign: X-SIGN
minecraft:
  work-dir: /www/minecraft/VanillaEra:CulinaryJourney2.5.1â€“Server
  run-script: ./run.sh
